// <auto-generated />
using FullStack.api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(dbClass))]
    partial class dbClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullStack.api.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int?>("InvesterId")
                        .HasColumnType("int");

                    b.Property<double?>("NumberOfRooms")
                        .HasColumnType("float");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Profit")
                        .HasColumnType("int");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("SquareMeter")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Apartmen__3214EC070C62DEB7");

                    b.HasIndex("InvesterId");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Apartment", (string)null);
                });

            modelBuilder.Entity("FullStack.api.Investor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength()
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("InvestmentAmount")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength()
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK__Investor__3214EC07B49F5B5C");

                    b.ToTable("Investor", (string)null);
                });

            modelBuilder.Entity("FullStack.api.Project", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("NumberOfApartments")
                        .HasColumnType("int");

                    b.Property<string>("ProjactName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Projects__3214EC07022465CE");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FullStack.api.Apartment", b =>
                {
                    b.HasOne("FullStack.api.Investor", "Invester")
                        .WithMany("Apartments")
                        .HasForeignKey("InvesterId")
                        .HasConstraintName("FK_Apartment_ToTable");

                    b.HasOne("FullStack.api.Project", "ProjectNumberNavigation")
                        .WithMany("Apartments")
                        .HasForeignKey("ProjectNumber")
                        .IsRequired()
                        .HasConstraintName("FK_Apartment_ToTable_1");

                    b.Navigation("Invester");

                    b.Navigation("ProjectNumberNavigation");
                });

            modelBuilder.Entity("FullStack.api.Investor", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("FullStack.api.Project", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
